/**
 * Elakolije / Univerexport leaf categories.
 * Edit `category` per row to match Pricely labels (Groceries, Drinks, Alcohol, …).
 * Regenerate (keeps your category mappings by sifkla): node scripts/extractElakolijeCategories.js
 */
export type UniverexportCategoryEntry = {
  sifkla: string;
  label: string;
  category: string;
};

export const UNIVEREXPORT_COMPLETE_CATEGORIES: UniverexportCategoryEntry[] = [
  { sifkla: "1000110", label: "TRADICIONALNO VOĆE", category: "Fruits & Vegetables" },
  { sifkla: "1000120", label: "JUŽNO VOĆE", category: "Fruits & Vegetables" },
  { sifkla: "1000130", label: "CITRUSI", category: "Fruits & Vegetables" },
  { sifkla: "1000210", label: "SVEŽE POVRĆE", category: "Fruits & Vegetables" },
  { sifkla: "1000410", label: "SUVO GROŽĐE", category: "Fruits & Vegetables" },
  { sifkla: "1000420", label: "SUVE ŠLJIVE", category: "Fruits & Vegetables" },
  { sifkla: "1000430", label: "OSTALO SUVO VOĆE", category: "Fruits & Vegetables" },
  { sifkla: "2000110", label: "HLEB", category: "Bakery" },
  { sifkla: "2000125", label: "TOST DVOPEK GRISINE", category: "Bakery" },
  { sifkla: "2000140", label: "RAZNE VRSTE PECIVA", category: "Bakery" },
  { sifkla: "2000220", label: "KOLAČI PAKOVANI I KOMADNI", category: "Bakery" },
  { sifkla: "2000310", label: "SVEŽE MESO", category: "Meat & Fish" },
  { sifkla: "2000410", label: "DIMLJENO I SUHOMESNATO", category: "Meat & Fish" },
  { sifkla: "2000420", label: "VIRŠLE I KOBASICE", category: "Meat & Fish" },
  { sifkla: "2000425", label: "SALAME", category: "Meat & Fish" },
  { sifkla: "2000435", label: "SLANINA ČVARCI MAST", category: "Meat & Fish" },
  { sifkla: "2000440", label: "VAKUUM I SLAJS PROIZVODI", category: "Meat & Fish" },
  { sifkla: "3000110", label: "MLEKO KRAVLJE SVEŽE", category: "Milk and egg products" },
  { sifkla: "3000120", label: "MLEKO KRAVLJE DUGOTRAJNO", category: "Milk and egg products" },
  { sifkla: "3000135", label: "MLEKO ČOKOLADNO", category: "Milk and egg products" },
  { sifkla: "3000190", label: "OSTALI NAPICI OD MLEKA", category: "Milk and egg products" },
  { sifkla: "3000210", label: "JOGURT", category: "Milk and egg products" },
  { sifkla: "3000220", label: "JOGURT VOĆNI", category: "Milk and egg products" },
  { sifkla: "3000225", label: "KEFIR", category: "Milk and egg products" },
  { sifkla: "3000230", label: "KISELO MLEKO", category: "Milk and egg products" },
  { sifkla: "3000310", label: "PUDING I SUTLIJAŠ", category: "Milk and egg products" },
  { sifkla: "3000315", label: "MILK ŠEJK", category: "Milk and egg products" },
  { sifkla: "3000410", label: "KISELA PAVLAKA", category: "Milk and egg products" },
  { sifkla: "3000420", label: "MILERAM", category: "Milk and egg products" },
  { sifkla: "3000425", label: "PAPRIKA U PAVLACI", category: "Milk and egg products" },
  { sifkla: "3000430", label: "SLATKA PAVLAKA I PAVLAKA ZA KUVANJE", category: "Milk and egg products" },
  { sifkla: "3000510", label: "BELI I MLADI SIR", category: "Milk and egg products" },
  { sifkla: "3000515", label: "POLUTVRDI SIR", category: "Milk and egg products" },
  { sifkla: "3000520", label: "TVRDI SIR", category: "Milk and egg products" },
  { sifkla: "3000525", label: "TOPLJENI SIR", category: "Milk and egg products" },
  { sifkla: "3000530", label: "MEŠOVITI PROIZVODI", category: "Milk and egg products" },
  { sifkla: "3000535", label: "SIRNI NAMAZI", category: "Milk and egg products" },
  { sifkla: "3000590", label: "OSTALE VRSTE SIRA", category: "Milk and egg products" },
  { sifkla: "3000610", label: "JAJA KOKOŠIJA", category: "Milk and egg products" },
  { sifkla: "3000710", label: "SVEZE KORE", category: "Groceries" },
  { sifkla: "3000715", label: "PODLOGE ZA PICU I TORTILJE", category: "Groceries" },
  { sifkla: "3000725", label: "SVEŽ KVASAC", category: "Milk and egg products" },
  { sifkla: "3000810", label: "MAJONEZ", category: "Groceries" },
  { sifkla: "3000820", label: "SENF", category: "Groceries" },
  { sifkla: "3000825", label: "REN", category: "Groceries" },
  { sifkla: "3000910", label: "MARGARIN", category: "Milk and egg products" },
  { sifkla: "3000920", label: "MASLAC", category: "Milk and egg products" },
  { sifkla: "4000110", label: "SUNCOKRETOVO ULJE", category: "Groceries" },
  { sifkla: "4000115", label: "MASLINOVO ULJE", category: "Groceries" },
  { sifkla: "4000120", label: "BILJNA ULJA OSTALA", category: "Groceries" },
  { sifkla: "4000210", label: "ALKOHOLNO SIRĆE", category: "Groceries" },
  { sifkla: "4000215", label: "VOĆNO SIRĆE", category: "Groceries" },
  { sifkla: "4000310", label: "BRAŠNO PŠENIČNO", category: "Groceries" },
  { sifkla: "4000320", label: "BRAŠNO KUKURUZNO", category: "Groceries" },
  { sifkla: "4000325", label: "INTEGRALNO HELJDINO I CRNO BRAŠNO", category: "Groceries" },
  { sifkla: "4000330", label: "GRIZ", category: "Groceries" },
  { sifkla: "4000390", label: "OSTALO BRAŠNO I GRIZ", category: "Groceries" },
  { sifkla: "4000410", label: "KUKURUZNA PALENTA", category: "Groceries" },
  { sifkla: "4000415", label: "INTEGRALNA PALENTA", category: "Groceries" },
  { sifkla: "4000425", label: "PREZLA", category: "Groceries" },
  { sifkla: "4000510", label: "ŠEĆER", category: "Groceries" },
  { sifkla: "4000520", label: "SO", category: "Groceries" },
  { sifkla: "4000610", label: "PIRINAČ", category: "Groceries" },
  { sifkla: "4000615", label: "ŽITARICE", category: "Fruits & Vegetables" },
  { sifkla: "4000710", label: "TESTENINA", category: "Groceries" },
  { sifkla: "4000725", label: "INSTANT PASTE I NUDLE", category: "Groceries" },
  { sifkla: "4000810", label: "SOSEVI", category: "Groceries" },
  { sifkla: "4000820", label: "PRELIVI", category: "Groceries" },
  { sifkla: "4000910", label: "BISTRE SUPE", category: "Groceries" },
  { sifkla: "4000915", label: "KREM SUPE", category: "Groceries" },
  { sifkla: "4000920", label: "PARADAJZ SUPE", category: "Groceries" },
  { sifkla: "4000925", label: "SUPE ZA DECU", category: "Groceries" },
  { sifkla: "4000930", label: "POSNE SUPE", category: "Groceries" },
  { sifkla: "4000935", label: "PARADAJZ ČORBE I OSTALE ČORBE", category: "Groceries" },
  { sifkla: "4000940", label: "INSTANT SUPE I KNEDLE", category: "Groceries" },
  { sifkla: "4000945", label: "SUPE U KOCKI", category: "Groceries" },
  { sifkla: "4001010", label: "BIBER", category: "Groceries" },
  { sifkla: "4001015", label: "MLEVENA I TUCANA PAPRIKA", category: "Groceries" },
  { sifkla: "4001020", label: "ZAČINI I DODACI JELIMA", category: "Groceries" },
  { sifkla: "4001025", label: "TRADICIONALNI ZAČINI", category: "Groceries" },
  { sifkla: "4001035", label: "SODA BIKARBONA I KONZERVANSI", category: "Groceries" },
  { sifkla: "4001040", label: "LIMUNTUS I VINOBRAN", category: "Groceries" },
  { sifkla: "4001110", label: "KEČAP", category: "Groceries" },
  { sifkla: "4001120", label: "PARADAJZ SOK", category: "Groceries" },
  { sifkla: "4001125", label: "PASIRANI PARADAJZ I PELAT", category: "Groceries" },
  { sifkla: "4001210", label: "UKRASI AROME I BOJE", category: "Groceries" },
  { sifkla: "4001215", label: "GOTOVE SMESE", category: "Groceries" },
  { sifkla: "4001220", label: "MLEKO U PRAHU", category: "Groceries" },
  { sifkla: "4001225", label: "ŠLAG I DRUGI DODACI ZA PRIPREMU KOLAČA", category: "Groceries" },
  { sifkla: "4001230", label: "PUDING", category: "Groceries" },
  { sifkla: "4001240", label: "KORE ZA TORTE I KOLAČE", category: "Groceries" },
  { sifkla: "4001245", label: "OBLATNE KORNETI I KORPICE", category: "Groceries" },
  { sifkla: "5000215", label: "BILJNI NAPICI", category: "Milk and egg products" },
  { sifkla: "5000410", label: "ORGANSKO ULJE", category: "Groceries" },
  { sifkla: "5000415", label: "ORGANSKO SIRĆE", category: "Groceries" },
  { sifkla: "5000465", label: "ORGANSKE KAŠE I PAHULJICE", category: "Healthy Food" },
  { sifkla: "5000470", label: "ORGANSKE ŽITARICE", category: "Healthy Food" },
  { sifkla: "5000475", label: "ORGANSKI PEKMEZ DŽEM I SLATKO", category: "Fruits & Vegetables" },
  { sifkla: "5000620", label: "ŽITARICE I MAHUNARKE", category: "Fruits & Vegetables" },
  { sifkla: "5000625", label: "ZASLAĐIVAČI I ŠEĆERI", category: "Groceries" },
  { sifkla: "5000720", label: "PAHULJICE OVSENE KAŠE I PIREI", category: "Healthy Food" },
  { sifkla: "5000825", label: "VOĆNI I KREM NAMAZI", category: "Healthy Food" },
  { sifkla: "5000830", label: "MEŠOVITI PROIZVODI", category: "Healthy Food" },
  { sifkla: "5000910", label: "INTEGRALNI I HRONO KEKS", category: "Sweets and Snacks" },
  { sifkla: "5000915", label: "INTEGRALNE PLOČICE I SLANIŠI", category: "Sweets and Snacks" },
  { sifkla: "5000920", label: "EKSPANDIRANI PROIZVODI", category: "Healthy Food" },
  { sifkla: "5000925", label: "SLATKIŠI BEZ ŠEĆERA", category: "Sweets and Snacks" },
  { sifkla: "6000110", label: "SMRZNUTO VOĆE", category: "Frozen products" },
  { sifkla: "6000115", label: "SMRZNUTO POVRĆE", category: "Frozen products" },
  { sifkla: "6000210", label: "SMRZNUTE KNEDLE TESTO I PECIVA", category: "Frozen products" },
  { sifkla: "6000215", label: "SMRZNUTO TESTO RAZNO", category: "Frozen products" },
  { sifkla: "6000220", label: "SMRZNUTI BUREK", category: "Frozen products" },
  { sifkla: "6000225", label: "SMRZNUTA PITA", category: "Frozen products" },
  { sifkla: "6000230", label: "PODLOGE ZA PICU I SMRZNUTA PICA", category: "Frozen products" },
  { sifkla: "6000290", label: "OSTALA SMRZNUTA TESTA I PECIVA", category: "Frozen products" },
  { sifkla: "6000310", label: "SLADOLEDI", category: "Frozen products" },
  { sifkla: "6000410", label: "PILEĆI PROGRAM", category: "Frozen products" },
  { sifkla: "6000435", label: "MORSKA RIBA I PLODOVI MORA", category: "Frozen products" },
  { sifkla: "6000440", label: "PANIRANA I DIMLJENA RIBA", category: "Frozen products" },
  { sifkla: "6000510", label: "GOTOVA JELA", category: "Groceries" },
  { sifkla: "6000610", label: "KISELA PAPRIKA I FEFERONE", category: "Fruits & Vegetables" },
  { sifkla: "6000615", label: "AJVAR", category: "Fruits & Vegetables" },
  { sifkla: "6000620", label: "CVEKLA I MEŠANA SALATA", category: "Fruits & Vegetables" },
  { sifkla: "6000625", label: "KISELI KRASTAVCI", category: "Fruits & Vegetables" },
  { sifkla: "6000630", label: "MASLINE", category: "Fruits & Vegetables" },
  { sifkla: "6000635", label: "ŠAMPINJONI", category: "Fruits & Vegetables" },
  { sifkla: "6000690", label: "OSTALO POVRĆE", category: "Fruits & Vegetables" },
  { sifkla: "6000710", label: "KOMPOT ANANAS", category: "Fruits & Vegetables" },
  { sifkla: "6000715", label: "KOMPOT BRESKVA", category: "Fruits & Vegetables" },
  { sifkla: "6000810", label: "MARMELADE", category: "Fruits & Vegetables" },
  { sifkla: "6000815", label: "PEKMEZI", category: "Fruits & Vegetables" },
  { sifkla: "6000820", label: "DŽEMOVI", category: "Fruits & Vegetables" },
  { sifkla: "6000910", label: "MED", category: "Groceries" },
  { sifkla: "6001010", label: "MESNI NAREZAK U KONZERVI", category: "Meat & Fish" },
  { sifkla: "6001020", label: "PAŠTETE U KONZERVI", category: "Meat & Fish" },
  { sifkla: "6001110", label: "RIBLJE PAŠTETE", category: "Meat & Fish" },
  { sifkla: "6001115", label: "SARDINE", category: "Meat & Fish" },
  { sifkla: "6001120", label: "TUNJEVINA U KONZERVI", category: "Meat & Fish" },
  { sifkla: "6001125", label: "SKUŠA I HARINGA", category: "Meat & Fish" },
  { sifkla: "7000110", label: "ŽVAKE", category: "Sweets and Snacks" },
  { sifkla: "7000115", label: "LIZALICE", category: "Sweets and Snacks" },
  { sifkla: "7000120", label: "BOMBONE", category: "Sweets and Snacks" },
  { sifkla: "7000125", label: "RATLUK I ŽELE", category: "Sweets and Snacks" },
  { sifkla: "7000210", label: "KEKS I BISKVITI", category: "Sweets and Snacks" },
  { sifkla: "7000220", label: "PIŠKOTE", category: "Sweets and Snacks" },
  { sifkla: "7000230", label: "ROLERI I BATONI", category: "Sweets and Snacks" },
  { sifkla: "7000235", label: "ROLATI I PAKOVANI KOLAČI", category: "Sweets and Snacks" },
  { sifkla: "7000310", label: "ŠTRUDLE", category: "Sweets and Snacks" },
  { sifkla: "7000315", label: "KROASANI", category: "Sweets and Snacks" },
  { sifkla: "7000410", label: "ČOKOLADA", category: "Sweets and Snacks" },
  { sifkla: "7000420", label: "ČOKOLADA ZA KUVANJE", category: "Sweets and Snacks" },
  { sifkla: "7000425", label: "SITNE ČOKOLADICE I PAKOVANJA", category: "Sweets and Snacks" },
  { sifkla: "7000430", label: "KREM PROIZVODI", category: "Sweets and Snacks" },
  { sifkla: "7000510", label: "BOMBONJERE", category: "Sweets and Snacks" },
  { sifkla: "7000515", label: "PRALINE", category: "Sweets and Snacks" },
  { sifkla: "7000610", label: "ČIPS", category: "Sweets and Snacks" },
  { sifkla: "7000620", label: "ŠTAPIĆI", category: "Sweets and Snacks" },
  { sifkla: "7000630", label: "KREKERI", category: "Sweets and Snacks" },
  { sifkla: "7000635", label: "SMOKI I FLIPS", category: "Sweets and Snacks" },
  { sifkla: "7000640", label: "KOKICE I KUKURUZ", category: "Sweets and Snacks" },
  { sifkla: "7000645", label: "BAKE ROLLS", category: "Sweets and Snacks" },
  { sifkla: "7000650", label: "PERECE I RIBICE", category: "Sweets and Snacks" },
  { sifkla: "7000710", label: "KIKIRIKI", category: "Sweets and Snacks" },
  { sifkla: "7000720", label: "PISTAĆI", category: "Sweets and Snacks" },
  { sifkla: "7000725", label: "BADEM LEŠNIK ORASI", category: "Healthy Food" },
  { sifkla: "7000730", label: "BELE I CRNE SEMENKE", category: "Healthy Food" },
  { sifkla: "7000735", label: "MIKSEVI", category: "Sweets and Snacks" },
  { sifkla: "7000810", label: "MUSLI", category: "Healthy Food" },
  { sifkla: "7000815", label: "CORN FLAKES", category: "Healthy Food" },
  { sifkla: "7000890", label: "OSTALE CERALIJE", category: "Healthy Food" },
  { sifkla: "8000110", label: "KAŠICE", category: "Baby Care" },
  { sifkla: "8000120", label: "SOKIĆI", category: "Baby Care" },
  { sifkla: "8000130", label: "DESERTI", category: "Baby Care" },
  { sifkla: "8000135", label: "CEREALIJE", category: "Baby Care" },
  { sifkla: "8000230", label: "PELENE", category: "Baby Care" },
  { sifkla: "8000320", label: "SAPUNI", category: "Baby Care" },
  { sifkla: "8000330", label: "ŠAMPONI", category: "Baby Care" },
  { sifkla: "8000350", label: "PUDERI KREME I MAST", category: "Baby Care" },
  { sifkla: "8000355", label: "PASTE ZA ZUBE", category: "Baby Care" },
  { sifkla: "8000360", label: "VLAŽNE MARAMICE", category: "Baby Care" },
  { sifkla: "9000110", label: "RAKIJA", category: "Alcohol" },
  { sifkla: "9000120", label: "DŽIN I RUM", category: "Alcohol" },
  { sifkla: "9000125", label: "VODKA", category: "Alcohol" },
  { sifkla: "9000135", label: "WHISKY I BURBON", category: "Alcohol" },
  { sifkla: "9000140", label: "BRENDI I KONJAK", category: "Alcohol" },
  { sifkla: "9000145", label: "LIKERI I PELINKOVAC", category: "Alcohol" },
  { sifkla: "9000150", label: "VINJAK", category: "Alcohol" },
  { sifkla: "9000190", label: "KOKTEL", category: "Alcohol" },
  { sifkla: "9000210", label: "LIMENKA", category: "Alcohol" },
  { sifkla: "9000220", label: "STAKLO POVRATNA I NEPOVRATNA AMBALAŽA", category: "Alcohol" },
  { sifkla: "9000230", label: "PET AMBALAŽA", category: "Alcohol" },
  { sifkla: "9000250", label: "RADLERI", category: "Alcohol" },
  { sifkla: "9000255", label: "STRANA I ZANATSKA PIVA", category: "Alcohol" },
  { sifkla: "9000310", label: "BELA VINA", category: "Alcohol" },
  { sifkla: "9000320", label: "CRVENA VINA", category: "Alcohol" },
  { sifkla: "9000330", label: "ROZE VINO", category: "Alcohol" },
  { sifkla: "9000340", label: "AROMATIZOVANA VINA", category: "Alcohol" },
  { sifkla: "9000345", label: "PENUŠAVA VINA I ŠAMPANJAC", category: "Alcohol" },
  { sifkla: "9000350", label: "CIDERI", category: "Alcohol" },
  { sifkla: "9000420", label: "NEGAZIRANA VODA", category: "Drinks" },
  { sifkla: "9000430", label: "GAZIRANA VODA", category: "Drinks" },
  { sifkla: "9000510", label: "GAZIRANO PIĆE", category: "Drinks" },
  { sifkla: "9000520", label: "NEGAZIRANO PIĆE", category: "Drinks" },
  { sifkla: "9000530", label: "ENERGETSKI NAPICI", category: "Drinks" },
  { sifkla: "9000535", label: "INSTANT NAPICI", category: "Drinks" },
  { sifkla: "9000540", label: "LEDENI CAJ", category: "Drinks" },
  { sifkla: "9000545", label: "SIRUPI I VOĆNI NAPICI", category: "Drinks" },
  { sifkla: "9000610", label: "DOMAĆA KAFA", category: "Drinks" },
  { sifkla: "9000620", label: "ESPRESSO", category: "Drinks" },
  { sifkla: "9000625", label: "INSTANT I FILTER KAFA", category: "Drinks" },
  { sifkla: "9000630", label: "CAPPUCINO", category: "Drinks" },
  { sifkla: "9000640", label: "GOTOVI NAPICI", category: "Drinks" },
  { sifkla: "9000650", label: "TRADICIONALNI ČAJEVI", category: "Drinks" },
  { sifkla: "9000710", label: "TOPLA ČOKOLADA I MILKŠEJK", category: "Drinks" },
  { sifkla: "9000715", label: "KAKAO NAPICI", category: "Drinks" },
  { sifkla: "a000110", label: "PASTE ZA ZUBE", category: "Personal Care" },
  { sifkla: "a000115", label: "ČETKICE I KONAC ZA ZUBE", category: "Personal Care" },
  { sifkla: "a000120", label: "SREDSTVA ZA ISPIRANJE I OSVEŽAVANJE USTA", category: "Personal Care" },
  { sifkla: "a000210", label: "KREMA ZA LICE", category: "Personal Care" },
  { sifkla: "a000230", label: "MLEKO LOSIONI I TONICI", category: "Personal Care" },
  { sifkla: "a000245", label: "BALZAM I LABELO ZA USNE", category: "Personal Care" },
  { sifkla: "a000310", label: "KUPKE I GELOVI", category: "Personal Care" },
  { sifkla: "a000320", label: "SAPUNI ZA TELO I RUKE", category: "Personal Care" },
  { sifkla: "a000335", label: "MLEKA ULJE I LOSIONI", category: "Personal Care" },
  { sifkla: "a000350", label: "KREME ZA RUKE I TELO", category: "Personal Care" },
  { sifkla: "a000360", label: "MEDICINSKI BALZAMI I KREME", category: "Personal Care" },
  { sifkla: "a000410", label: "ŠAMPONI ZA KOSU", category: "Personal Care" },
  { sifkla: "a000420", label: "MASKE REGENERATORI I BALZAMI", category: "Personal Care" },
  { sifkla: "a000430", label: "SREDSTVA ZA OBLIKOVANJE KOSE", category: "Personal Care" },
  { sifkla: "a000435", label: "SREDSTVA ZA BOJENJE KOSE", category: "Personal Care" },
  { sifkla: "a000610", label: "DEZODORANSI", category: "Personal Care" },
  { sifkla: "a000710", label: "PENE I GELOVI ZA BRIJANJE", category: "Personal Care" },
  { sifkla: "a000720", label: "LOSIONI", category: "Personal Care" },
  { sifkla: "a000730", label: "PRIBOR ZA BRIJANJE I BRIJAČI", category: "Personal Care" },
  { sifkla: "a000735", label: "PRIBOR ZA DEPILACIJU", category: "Personal Care" },
  { sifkla: "a000810", label: "TOALETNI PAPIR", category: "Personal Care" },
  { sifkla: "a000820", label: "UBRUSI", category: "Personal Care" },
  { sifkla: "a000830", label: "SALVETE", category: "Personal Care" },
  { sifkla: "a000835", label: "PAPIRNE MARAMICE", category: "Personal Care" },
  { sifkla: "a000845", label: "VLAŽNE MARAMICE", category: "Personal Care" },
  { sifkla: "a000850", label: "VLAŽNI TOALETNI PAPIR", category: "Personal Care" },
  { sifkla: "a000910", label: "VATA I TUFERI", category: "Personal Care" },
  { sifkla: "a000915", label: "ŠTAPICI ZA UŠI", category: "Personal Care" },
  { sifkla: "a000925", label: "HIGIJENSKI ULOŠCI", category: "Personal Care" },
  { sifkla: "a000935", label: "DNEVNI ULOŠCI", category: "Personal Care" },
  { sifkla: "a000945", label: "TAMPONI", category: "Personal Care" },
  { sifkla: "a001010", label: "SREDSTVO ZA ZAŠTITU OD SUNCA - TELO", category: "Personal Care" },
  { sifkla: "a001025", label: "SREDSTVA ZA POTAMNJIVANJE", category: "Personal Care" },
  { sifkla: "b000110", label: "PRAŠAK ZA VEŠ", category: "Home Care" },
  { sifkla: "b000120", label: "TEČNI DETERDŽENT ZA VEŠ", category: "Home Care" },
  { sifkla: "b000130", label: "TABLETE I KAPSULE", category: "Home Care" },
  { sifkla: "b000150", label: "OMEKŠIVAČI", category: "Home Care" },
  { sifkla: "b000160", label: "DESTILOVANA VODA I ŠTIRAK", category: "Home Care" },
  { sifkla: "b000165", label: "IZBELJIVAČI I SKIDAČI FLEKA", category: "Home Care" },
  { sifkla: "b000170", label: "OPREMA ZA VEŠ OSTALO", category: "Home Care" },
  { sifkla: "b000210", label: "DETERDŽENTI ZA SUDOVE", category: "Home Care" },
  { sifkla: "b000220", label: "DETERĐŽENTI ZA MAŠINSKO PRANJE SUĐA", category: "Home Care" },
  { sifkla: "b000230", label: "SREDSTVA ZA ČIŠĆENJE KUHINJE", category: "Home Care" },
  { sifkla: "b000310", label: "SREDSTVA ZA ČIŠĆENJE PODOVA", category: "Home Care" },
  { sifkla: "b000315", label: "SREDSTVA ZA ČIŠĆENJE TEPIHA", category: "Home Care" },
  { sifkla: "b000320", label: "SREDSTVA ZA ČIŠĆENJE STAKLA", category: "Home Care" },
  { sifkla: "b000325", label: "SREDSTVA ZA ČIŠĆENJE NAMEŠTAJA", category: "Home Care" },
  { sifkla: "b000410", label: "SANITARIJE", category: "Home Care" },
  { sifkla: "b000415", label: "SREDSTVA ZA ČIŠCENJE SLIVNIKA", category: "Home Care" },
  { sifkla: "b000420", label: "WC OSVEŽIVAČI", category: "Home Care" },
  { sifkla: "b000510", label: "ZA OTKLANJANJE BUĐI", category: "Home Care" },
  { sifkla: "b000520", label: "OSVEŽIVAČI PROSTORA", category: "Home Care" },
  { sifkla: "b000525", label: "ZA ODRŽAVANJE DOMAĆINSTVA", category: "Home Care" },
  { sifkla: "b000610", label: "SREDSTVA ZA ODRŽAVANJE OBUĆE", category: "Home Care" },
  { sifkla: "b000710", label: "SREDSTVA PROTIV INSEKATA", category: "Home Care" },
  { sifkla: "b000715", label: "ZAMKE PROTIV sINSEKATA", category: "Home Care" },
  { sifkla: "b000720", label: "SREDSTVA I NARUKVICE ZA ZAŠTITU OD INSEKATA", category: "Home Care" },
  { sifkla: "c000410", label: "FOLIJE KESE PAPIR ZA PEČENJE", category: "Home Care" },
  { sifkla: "c000415", label: "KESE ZA SMEĆE", category: "Home Care" },
  { sifkla: "c000510", label: "ZAŠTITNA OPREMA I RUKAVICE", category: "Home Care" },
  { sifkla: "c000520", label: "SUNĐERI I TRULEKS KRPE", category: "Home Care" },
  { sifkla: "c000525", label: "ŽICE ZA SUĐE", category: "Home Care" },
  { sifkla: "c000530", label: "KRPE ZA DOMAĆINSTVO", category: "Home Care" },
  { sifkla: "c001110", label: "HRANA", category: "Pet Care" },
  { sifkla: "c001425", label: "PREZERVATIVI I LUBRIKANTI", category: "Personal Care" },

];
