/**
 * Zlatan Trag "Opis robe" (leaf group shown on proveracena.zlatantrag.rs) → Pricely category.
 *
 * Descriptions not listed here are skipped by the scraper (non-grocery: toys, clothing,
 * tobacco, stationery, tableware, seasonal programs…). Matching ignores case/diacritics.
 * - Add a description to a list to start scraping it.
 * - Move it to another list to remap.
 */
import { normalizeName } from "../productService";

const GROUPS: Record<string, string[]> = {
  "Sweets and Snacks": [
    "Punjeni i senvic keks", "Vafli", "Mlecne Cokolade", "Cokoladice i stanglice", "Cips",
    "Bombonjere i praline", "Smoki i flips", "Cvrsti keks", "Zvake",
    "Mafini, tortice, cake barovi i meki kolaci", "Bombone sitne i komprimati", "Kreker slani",
    "Bombone tvrde", "Bombone gumene", "Kroasani", "integralni keks", "Kremovi",
    "Bombone punjene cokoladom-filom-kikiriki", "Lizalice", "Tortilja cips", "Cokoladna jaja",
    "Strudle", "Bananice", "Biskviti", "Mleveni keks", "Ostali keks", "Medenjaci",
    "grisini - obicni", "grisini - punjeni", "grisini integralni", "Perece slane",
    "Kokice spremne za jelo", "Kokice za mikrotalasnu", "Crne cokolade", "stapici od peciva razni",
    "Bombone karamele", "Krem table", "Bombone zele", "Cokoladne figure", "Bombone penaste",
    "Coko smoki", "Alva", "Ratluk", "Coko kuglice i pillows", "Ekspandirani cips",
    "Flips sa igrackom", "Kremovi-stapici, dipsi, sa igrackom", "Slani mix ribice/perece/stapic",
    "Ribice slane", "Piskote", "Rolati", "Bombone organic vegan", "Zele kocke, kriske i figure",
    "Penasti dezerti", "Slana peciva",
    "Apetisani-Kikiriki przeni", "Apetisani-Kikiriki peceni", "Apetisani-ostali mix",
    "Apetisani-badem", "Apetisani-Suncokret sa ljuskom", "Apetisani-Seme bundeve sa ljuskom",
    "Apetisani-Suncokret ocisceni", "Apetisani-Indijski orah", "Apetisani-lesnik",
    "Apetisani-Pistaci", "Apetisani-Kikiriki kuglice", "Apetisani-Kikiriki blansirani",
    "Apetisani-Kikiriji diet", "Apetisani-Kikiriki u ljusci",
  ],
  Drinks: [
    "Negazirani sokovi pet", "Gazirani sokovi", "Negazirani sokovi brik", "Negazirani sokovi staklo",
    "Instant kafa", "Energetska pica", "Negazirane vode", "Tradicionalna kafa", "Cajevi biljni",
    "Cajevi vocni", "Cajevi zeleni", "Cajevi crni", "Ledeni cajevi", "Ready to drink kafa",
    "Vitaminski napici", "Funkcionalne vode gazirane", "Funkcionalne vode negazirane", "Sokovi",
    "Gazirane vode", "Sirupi", "Filter kafa", "Kakao i dodaci mleku", "Topla cokolada",
    "Espresso kafa", "Setovi kafa", "Deciji sampanjac", "Kvas", "Instant sokovi",
  ],
  Alcohol: [
    "Crno vino", "Belo vino", "Roze vino", "Aromatizovano vino", "Penusavo vino",
    "Ostala zestoka pica", "Rakije", "Viski", "Likeri", "Pelinkovci", "Vodka", "Dzin", "Tekila",
    "Svetla piva Limenka", "Svetla piva -Staklo", "Svetla piva -pet", "Tamna piva-Limenka",
    "Pivo svetlo-Bure", "Bezalkoholna piva", "Radleri-Staklo", "Radleri-Limenka",
    "Radleri-Bezalkoholni",
  ],
  "Milk and egg products": [
    "Mlecni dezerti", "Vocni jogurti", "Mlecni napici", "Dugotrajno mleko",
    "Dugotrajno čokoladno mleko", "Sveze mleko", "Mleko u prahu", "Namazni sirevi",
    "Jogurt do 1", "Jogurt do 1.5", "Jogurt do 180", "Jogurt do 400", "Jogurt do 500", "Jogurt do 2",
    "Grcki jogurti", "Kiselo mleko do 180", "Kiselo mleko do 400", "Kiselo mleko do 700", "Kefir",
    "Krem.pavl.slana,tecna", "Krem.pavl.slatka,tecna,sprej", "Pavlaka do 180", "Pavlaka do 400",
    "Pavlaka do 700", "Pavlaka do 1000", "Dodaci za kafu i slag sprej", "Maslac", "Mlecni snack",
    "Kackavalj kravlja m.mast kg", "Kackavalj mlecna mast slice", "Kackavalj mlecna mast ribani",
    "Kackavalj mlecna mast kom", "Kackavalj mlecna mast ostali kom",
    "Kackavalj mlecna mast ostali kg", "Kackavalj ovci.kozij.m.mast kg",
    "Kackavalj mesana mast slice", "Kackavalj mesana mast kom", "Kackavalj bilj,kravlj.m.mast kg",
    "Feta mlecna mast sir kom", "Feta mlecna mast sir kg", "Feta mesana mast sir kom",
    "Feta mesana mast sir kg", "Mladi mlecna mast sir kom", "Kriska kravlja m.mast sir kg",
    "Kriska kravlja m.mast sir kom", "Kriska mlecna mast ostali kom",
    "Kriska bilj,kravlj.m.mast sir kg", "Kriska ovci.kozij.m.mast sir kom",
    "Kriska biljn.kravlj.m.mast sir kom", "Mrvljeni mlecna mast sir kg",
    "Mrvljeni mlecna mast sir kom", "Mrvljeni mesana mast sir kom", "Topljeni sirevi za mazanje",
    "Topljeni sirevi rezani", "Sir zuti- biljnog porekla", "Sir beli-biljnog porekla",
    "Kajmak kom", "Kajmak kg", "Surutka", "Jaja 10/1", "Jaja 30/1",
  ],
  "Meat & Fish": [
    "Pasteta mesna u konzervi", "Pasteta u crevu", "Pasteta riblja posna", "Pasteta riblja masna",
    "Tuna obrok salata", "Tunjevina komadi i fileti u ulju", "Tunjevina komadici i usitnjena u ulju",
    "Tunjevina komadi i fileti sa dodacima", "Sardina i sardinela u ulju",
    "Sardina i sardinela sa dodacima", "Riba spec.komadi i fileti u ulju",
    "Riba spec.komadi i fileti sa dodacima", "Slajs program", "Trajne kobasice kg",
    "Trajne kobasice kom", "Nar.mesni,cureci,pileci,govedj", "Salame kom-pil.cur.par,pos,sa dod.",
    "Salame kom-sv.pariz,poseb,sa doda", "Salame kom-sve salame ex", "Salame kom-sv.sunke",
    "Salame kom-pil.cur.prsa,grudi,file", "Salame kom-sv.sunkarica,pizza,tost,butkica",
    "Salame kg-sv.pariz,poseb,sa dodac", "Salame kg-sve salame ex",
    "Salame kg-pil.cur.prsa,grudi,file", "Salame kg-sv.sunke", "Salame kg-pil.cur.par,pos,sadod.",
    "Salame kg-sv.sunkarica,pizza,tost,butkice", "Virsle kom-pilece i curece", "Virsle kom-svinjske",
    "Virsle kg-pilece i curece", "Kobasica kom", "Kobasica kg", "Dimljeni program kg-bareno meso bk",
    "Dimljeni program kg-suvo meso bk", "Dimljeni program kg-meso sk", "Dimljeni program kom-meso bk",
    "Slanina kg", "Slanina kom", "Prsuta kg", "Cvarci kom", "Cvarci kg", "Svinjska mast kom",
    "Svinjska mast kg", "Pilece sveze prerada", "Svinjsko sveze prerada", "Svinjske sveze iznutrice",
    "Zivinske sveze iznutrice", "Junece sveze", "Junece sveze iznutrice", "Jagnjeće sveze",
    "Praseće sveze", "Sveze rostilj meso sve", "Sprza kg",
  ],
  "Frozen products": [
    "Impulsni sladoledi", "Porodicni sladoledi", "Lizalice sladoledi", "Sladoleti u kesicama",
    "Smrznute torte", "Smrznuto testo slano", "Smrznuto testo slatko", "Smrznuto testo ostalo",
    "Smrznuto testo-dorada slatko", "Smrznuto testo-dorada slano", "Smrznuto testo-dorada ostalo",
    "Smrznuto testo-dorada hleb", "Smrznuto testo-dorada burek", "Smrznuto testo-pizza",
    "Smrznuto ostalo povrce", "Smrznuti krompir", "Smrznuto voce", "Smrznuti kesten",
    "Zamrznuta riba-panirano", "Zamrznuta riba-ostalo", "Zamrznuta riba-OSLICI",
    "Zamr.riba-morski plodovi i losos list", "Zamr.riba-panir.morski plodovi", "Roštilj meso smrznuto",
    "Smrznuto pileće meso", "Smrznuto svinjsko meso", "Zamrznuti",
  ],
  "Fruits & Vegetables": [
    "Povrce sveze", "Voce sveze", "Sampinjoni svezi", "Pasterizovano povrce", "Pasterizovano voce",
    "Masline", "Paprika u pavlaci", "Suvo voće upakovano", "Suvo voća na kg",
  ],
  Bakery: [
    "Tost hleb", "Spec.hleb-rezani-ostali", "Spec.hleb-rezani-osnovni", "Dnevni hleb-ostali",
    "Dnevni hleb-osnovni", "Rezani hleb-osnovni", "Somuni", "Peciva specijalna pakovana",
    "Slavski kolac,pogace", "Svezi kolaci", "Kolaci komadni svezi", "Slatka peciva", "Dvopek",
    "Tortilje",
  ],
  Groceries: [
    "Monozacini", "Bistre supe", "Krem supe", "Instant supe", "Koncentrati i bujoni", "Sosevi",
    "Sosovi za pripremu jela", "Paradajz sosevi", "Dodatak jelima - vegeta",
    "Zacinske smese i fix za jela", "Zacinske smese i fix za kolace", "Zacinske smese i fix za zimnicu",
    "Namenski zacini", "Paprika mlevena", "Kuhinjska so", "Morska so", "Gotova jela",
    "Polugotova jela", "Jela u kesici", "Pasteta povrce i salata", "Makarone", "Spageti", "Rezanci",
    "Fida", "Lazanje", "Sveza testenina", "Testenine instant", "Nudle", "Pirinac običan",
    "Prinac integralni", "Pasulj", "Socivo", "Soja", "Psenica", "Psenicno", "Kukuruzno",
    "Integralno i specijane vrste", "Griz", "Palenta", "Palenta instant", "Prezle", "Krompir pire",
    "Kecap blagi", "Kecap ljuti", "Kecap pizza", "Majonez delikates kesa", "Majonez delikates dojpak",
    "Majonez delikates boca", "Majonez delikates kantica", "Majonez delikates tegla",
    "Majonez delikates tuba", "Majonez light kesa", "Majonez light dojpak", "Majonez light kantica",
    "Senf", "Ren", "Prelivi", "Jabukovo sirce", "Alkoholno sirce", "Vinsko sirce", "Ostala sirca",
    "Maslinovo ulje", "Ostala ulja", "Suncokretovo ulje", "Namazni margarin", "Stoni margarin",
    "Med", "Secer kristal", "Secer u prahu", "Secer kocka", "Smedji secer", "Vanilin secer",
    "Prasak za pecivo", "Suvi kvasac", "Svezi kvasac", "Soda bikarbona", "Zelatin", "Gustin",
    "Esencija", "Arome i boje", "Ukrasi/dodaci za torte i kolac", "Oblande, kore i korpice",
    "Kore za pitu i baklavu", "Podloge za pizzu", "Palacinke", "Puding", "Slag krema u kesici",
    "Slag pena u kesici", "Krem table za kuvanje", "Cokolade za kuvanje mlecne", "Kokos",
    "Kukuruz kokicar", "Susam", "Priprema zimnice", "Vinobran", "Limontus", "Konzervans", "Siriste",
    "Stirak",
  ],
  "Healthy Food": [
    "Vitaminski dodaci ishrani", "Barovi protein, ceralije, raw, vocni", "Napitak-biljnog porekla",
    "Zamensko mleko", "Namaz humm.vegg", "Pirincane galete", "Kukuruzne galete", "Kase",
    "Kase Proteinske", "Musli", "Corn Flakes", "Pahuljice", "Zasladjivaci", "Pouchevi za odrasle",
  ],
  "Baby Care": [
    "Kasice slatke velike", "Kasice slatke male", "Kasice slane velike", "Kasice slane male",
    "Pire slatki mali", "Pire junior uzina 3+", "Instant hrana za bebe", "Pelene",
    "Vlazne maramice decije", "Kupka- sampon decija", "Sapun deciji", "Samponi deciji",
    "Kupke decije", "Losioni i mleko decije", "Baby ulje", "Tecni decji prasak", "Decji omeksivac",
    "Cajevi za decu",
  ],
  "Personal Care": [
    "Trajne boje za kosu", "Samponi", "Color samponi", "Samponi za suvo pranje kose", "Regeneratori",
    "Maske i tretmani za kosu", "Gel, vosak,ulja", "Lak za kosu", "Pena za kosu",
    "Hidrogeni i sred. za blajhanje", "Dezodoransi u spreju", "Dezodorans u stick-u ili kremi",
    "Dezodorans roll-on", "Toaletne vode i parfemi", "Setovi", "Paste za zube", "Cetkice za zube",
    "Vodice za ispiranje usta", "Oralna higijena", "Konac za ciscenje zuba", "Tusiranje i kupanje",
    "Tvrdi sapuni", "Tecni sapuni", "Piling za telo", "Losioni i mleka za telo", "Krema univerzalna",
    "Kreme", "Kreme za lice", "Sred.za ciscenje i odrz.lica", "Nega ruku",
    "Sredstva za negu usana labela", "Melemi", "Proizvodi za suncanje", "Puderi",
    "Skidac laka za nokte", "Pribor za lice i telo", "Tuferi", "Vata", "Stapici za usi",
    "Stapici za usi za odrasle", "Sredstva za brijanje (brijaci,depilatori,trimeri )",
    "Proizvodi za brijanje", "Proizvodi posle brijanja", "Sredstva za depilaciju", "Ciklusni ulosci",
    "Dnevni ulosci", "Tamponi", "Prezervativi", "Flasteri", "Papirne maramice",
    "Vlazne maramice dzepne", "Vlazne maramice Intimo", "Vlazne maramice Make Up",
    "Vlazne maramice ostalo",
  ],
  "Home Care": [
    "Praskasti deterdzenti", "Tecni deterdzenti", "Deter. u kapsulama", "Omeksivaci za ves",
    "Odstranjivaci fleka", "Ostala sredstva za ves", "Sapuni za rublje", "Sredstva za veš mašine",
    "Sredstva za peglanje", "Deterdzenti za rucno pranje po", "Sredstva za masine za posudje",
    "Kapsule za pranje posudja", "Tablete za pranje posudja", "Sredstva za podove",
    "Sredstva za stakla", "Sredstva za kupatilo", "Sredstva za ciscenje kuhinje",
    "Specijalizovana sred.za ciscej", "Sredstva za odmascivanje", "Sredstva za odvode",
    "Sredstva protiv kamenca", "Sredstva za dezinfekciju", "Abrazivna sredstva",
    "Sredstva za namestaj", "Vlazne maramice za namestaj", "Sredstva za obucu",
    "Osvezivaci za vazduh- sprej", "Osvezivaci za vazduh elektricni i refili",
    "Osvezivaci za vazduh-absorberi", "Osvezivaci za vazduh - stapici i ostalo", "Osvezivaci za WC",
    "Sredstva protiv komaraca", "Sredtva za zaštitu od insekata", "Insekticidi- protiv moljaca",
    "Toalet papir", "Vlazani toalet papir", "Ubrusi", "Salvete", "Kese za smece", "kese za zamrzivac",
    "Kese za led", "Kese za vakumiranje hrane", "Kese za pecenje", "Aluminijumske folije",
    "Prijanjajuca folija", "papir za pecenje", "Sundjeri", "Krpe", "Zice", "Brisaci i kofe",
    "Rukavice", "Oprema za susenje vesa", "Jednokratna upotreba",
  ],
  "Pet Care": [
    "Hrana za mace vlazna", "Hrana za mace suva", "Hrana za pse vlazna", "Hrana za pse suva",
    "Poslastice za pse", "Salama za zivotinje", "Oprema za kucne ljubimce",
    "Samponi za kucne ljubimce",
  ],
};

const CATEGORY_BY_KEY = new Map<string, string>();
for (const [category, descriptions] of Object.entries(GROUPS)) {
  for (const d of descriptions) CATEGORY_BY_KEY.set(normalizeName(d), category);
}

export function zlatanTragCategoryFor(description: string): string | null {
  return CATEGORY_BY_KEY.get(normalizeName(description)) ?? null;
}
